#!/bin/bash

# Comments here

source ./vars &> /dev/null

ETCD_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values=$ETCD_SEC_GROUP \
--output text)

MASTER_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values=$MASTERS_SEC_GROUP \
--output text)

aws ec2 authorize-security-group-ingress \
--group-id $ETCD_SEC_GRP_ID \
--protocol tcp \
--port 2379 \
--source-group $ETCD_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $ETCD_SEC_GRP_ID \
--protocol tcp \
--port 2379 \
--source-group $MASTER_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $ETCD_SEC_GRP_ID \
--protocol tcp \
--port 2380 \
--source-group $ETCD_SEC_GRP_ID

