#!/bin/bash

# Comments here

source ./vars &> /dev/null

while [ -z "$ROUTER_ELB_SEC_GRP_ID" ]; do
    ROUTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$ROUTER_ELB_SEC_GRP" \
    --output text)
done

while [ -z "$INFRA_NODE_SEC_GRP_ID" ]; do
    INFRA_NODE_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$INFRA_NODES_SEC_GROUP" \
    --output text)
done

aws ec2 authorize-security-group-ingress \
--group-id $INFRA_NODE_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--source-group $ROUTER_ELB_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $INFRA_NODE_SEC_GRP_ID \
--protocol tcp \
--port 80 \
--source-group $ROUTER_ELB_SEC_GRP_ID
