#!/bin/bash

# Comments here

source ./vars &> /dev/null

while [ -z "$INTERNAL_INTERNAL_MASTER_ELB_SEC_GRP_ID" ]; do
    INTERNAL_INTERNAL_MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$INTERNAL_MASTER_ELB_SEC_GRP" \
    --output text)
done

while [ -z "$NODES_SEC_GRP_ID" ]; do
    NODES_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$NODES_SEC_GROUP" \
    --output text)
done

while [ -z "$MASTER_SEC_GRP_ID" ]; do
    MASTER_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values=$MASTERS_SEC_GROUP \
    --output text)
done

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--source-group $NODES_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $INTERNAL_INTERNAL_MASTER_ELB_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--source-group $MASTER_SEC_GRP_ID
