#!/bin/bash

# Comments here

source ./vars &> /dev/null

while [ -z "$MASTER_ELB_SEC_GRP_ID" ]; do
    MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$MASTER_ELB_SEC_GRP" \
    --output text)
done

while [ -z "$MASTERS_SEC_GRP_ID" ]; do
    MASTERS_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$MASTERS_SEC_GROUP" \
    --output text)
done

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_ELB_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--cidr 0.0.0.0/0

aws ec2 authorize-security-group-egress \ 
--group-id $MASTER_ELB_SEC_GRP_ID --ip-permissions \
'[{"IpProtocol": "tcp", "FromPort": 443, "ToPort": 443, "UserIdGroupPairs": [{"GroupId": \"$MASTERS_SEC_GRP_ID\"}]}]'
