#!/bin/bash

# Comments here

source ./vars &> /dev/null

MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values="$MASTER_ELB_SEC_GRP" \
--output text)

while [ -z "$NODES_SEC_GRP_ID" ]; do
    NODES_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$NODES_SEC_GROUP" \
    --output text)
done

INTERNAL_MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values="$INTERNAL_MASTER_ELB_SEC_GRP" \
--output text)

MASTER_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values=$MASTERS_SEC_GROUP \
--output text)

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol udp \
--port 8053 \
--source-group $NODES_SEC_GRP_ID


aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 8053 \
--source-group $NODES_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--source-group $NODES_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--source-group $INTERNAL_MASTER_ELB_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--source-group $MASTER_ELB_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $MASTER_SEC_GRP_ID \
--protocol tcp \
--port 443 \
--source-group $MASTER_SEC_GRP_ID
