#!/bin/bash

# Comments here

source ./vars &> /dev/null

BASTION_SEC_GRP_ID=$(aws ec2 describe-security-groups \
--query SecurityGroups[].GroupId[] \
--filters Name=group-name,Values="$BASTION_SEC_GROUP" \
--output text)

while [ -z "$MASTER_SEC_GRP_ID" ]; do
    MASTER_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values=$MASTERS_SEC_GROUP \
    --output text)
done

while [ -z "$NODES_SEC_GRP_ID" ]; do
    NODES_SEC_GRP_ID=$(aws ec2 describe-security-groups \
    --query SecurityGroups[].GroupId[] \
    --filters Name=group-name,Values="$NODES_SEC_GROUP" \
    --output text)
done

aws ec2 authorize-security-group-ingress \
--group-id $NODES_SEC_GRP_ID \
--protocol tcp \
--port 4789 \
--source-group $NODES_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $NODES_SEC_GRP_ID \
--protocol tcp \
--port 10250 \
--source-group $MASTER_SEC_GRP_ID

aws ec2 authorize-security-group-ingress \
--group-id $NODES_SEC_GRP_ID \
--protocol tcp \
--port 22 \
--source-group $BASTION_SEC_GRP_ID
